const gate=document.querySelector('#gate'),main=document.querySelector('#main'),music=document.querySelector('#music'),video=document.querySelector('#video'),sound=document.querySelector('#sound');let wantsMusic=true;const ENDPOINT='https://script.google.com/macros/s/AKfycbyrXx4ZxlcyupXZIfN5n4G8rusngZ26a4lP7Af7IB_KNlKrVqz7dRGPJmmbmgMcYc7VwA/exec'; // Paste your deployed Google Apps Script Web App URL here.
const setSound=()=>{sound.textContent=wantsMusic?'♫ MUSIC ON':'♫ MUSIC OFF'};
document.querySelector('#open').addEventListener('click',async()=>{gate.hidden=true;main.hidden=false;window.scrollTo(0,0);if(wantsMusic){music.volume=.22;try{await music.play()}catch(e){wantsMusic=false;setSound()}}});
sound.addEventListener('click',async()=>{wantsMusic=!wantsMusic;setSound();if(wantsMusic&&!video.paused){return}if(wantsMusic){try{await music.play()}catch(e){wantsMusic=false;setSound()}}else music.pause()});
video.addEventListener('play',()=>{music.pause()});const resume=()=>{if(wantsMusic){music.volume=.22;music.play().catch(()=>{})}};video.addEventListener('ended',resume);video.addEventListener('pause',resume);
const form=document.querySelector('#date-form'),status=document.querySelector('#form-status');
function checkSaved(id){return new Promise((resolve,reject)=>{const cb='napisahCheck'+Date.now()+Math.floor(Math.random()*100000);const script=document.createElement('script');let done=false;const finish=(err,value)=>{if(done)return;done=true;clearTimeout(timer);delete window[cb];script.remove();err?reject(err):resolve(value)};window[cb]=value=>finish(null,value);script.onerror=()=>finish(new Error('Verification unavailable'));const timer=setTimeout(()=>finish(new Error('Verification timed out')),9000);script.src=ENDPOINT+'?action=status&id='+encodeURIComponent(id)+'&callback='+cb+'&t='+Date.now();document.head.appendChild(script)})}
async function waitForSave(id){for(let i=0;i<5;i++){const result=await checkSaved(id);if(result.saved)return true;if(result.error)throw Error(result.error);await new Promise(resolve=>setTimeout(resolve,1300))}return false}
function sendChoice(data){const iframe=document.createElement('iframe');iframe.name='date-submit-'+data.id;iframe.style.display='none';iframe.setAttribute('title','Date submission');document.body.appendChild(iframe);const post=document.createElement('form');post.method='POST';post.action=ENDPOINT;post.target=iframe.name;post.style.display='none';Object.entries(data).forEach(([key,value])=>{const input=document.createElement('input');input.type='hidden';input.name=key;input.value=value;post.appendChild(input)});document.body.appendChild(post);post.submit();post.remove();setTimeout(()=>iframe.remove(),30000)}
form.addEventListener('submit',async e=>{e.preventDefault();const date=document.querySelector('#date-input').value,time=document.querySelector('#time-input').value;if(date<'2026-10-13'||date>'2026-10-20'||!time){status.textContent='Please choose a date between 13–20 October 2026 and a time.';return}const button=form.querySelector('button');button.disabled=true;status.textContent='Saving our date…';try{const id=crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(36).slice(2);sendChoice({id,name:'Napisah',date,time});await new Promise(resolve=>setTimeout(resolve,1600));if(!await waitForSave(id))throw Error('Could not verify the saved date. Please contact Alfian.');document.querySelector('#confirmed-date').textContent=new Date(date+'T12:00:00').toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'});document.querySelector('#confirmed-time').textContent=time;document.querySelector('#confirmed').hidden=false;status.textContent='Saved successfully.';document.querySelector('#confirmed').scrollIntoView({behavior:'smooth'})}catch(err){status.textContent='Could not verify your choice. Please contact Alfian. '+err.message}finally{button.disabled=false}});

// V2 vinyl player follows actual soundtrack state, never the video audio.
const recordPlayer=document.querySelector('#record-player');
const recordToggle=document.querySelector('#record-toggle');
recordPlayer.hidden=true;
function syncRecord(){recordPlayer.hidden=main.hidden;const playing=!music.paused;recordPlayer.classList.toggle('playing',playing);recordToggle.textContent=playing?'PAUSE II':'PLAY ▶';recordToggle.setAttribute('aria-label',playing?'Pause Merindu':'Play Merindu')}
music.addEventListener('play',syncRecord);music.addEventListener('pause',syncRecord);
document.querySelector('#open').addEventListener('click',syncRecord);
recordToggle.addEventListener('click',async()=>{if(!music.paused){wantsMusic=false;music.pause()}else{wantsMusic=true;if(!video.paused)video.pause();try{await music.play()}catch(e){wantsMusic=false}}setSound();syncRecord()});
